version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: modular-monolith-postgres
    environment:
      POSTGRES_DB: modular_monolith_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    networks:
      - modular-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d modular_monolith_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modular-monolith-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/modular_monolith_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8080:8080"
    networks:
      - modular-network

volumes:
  postgres_data:

networks:
  modular-network:
    driver: bridge

